# Generated by Django 2.2.6 on 2021-06-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mydata',
            new_name='Myinfo',
        ),
    ]
