# Generated by Django 2.2.6 on 2021-06-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterprofiles', '0002_auto_20210623_0137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myinfo',
        ),
    ]
