# Generated by Django 2.2.6 on 2021-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
