# Generated by Django 2.2.6 on 2021-06-20 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210618_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='zipcode',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='orders',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
