# Generated by Django 2.2.6 on 2021-06-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210620_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
