# Generated by Django 2.2.6 on 2021-06-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210621_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='myuser',
        ),
    ]
