# Generated by Django 2.2.6 on 2021-06-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_myinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myinfo',
            old_name='users',
            new_name='user1',
        ),
    ]
